### PR TITLE
Updated for 1.13.2

### PR DESCRIPTION
**Pull request by crazygmr101**

### CODE REVIEW

**Review by Xericore — APPROVED** [review]
Thank you very much.

**Comment by crazygmr101** [comment]
@Xericore Do you have a contact email? I found another track plugin that had features like cart linking, and its too bloated for a small server, and I was wondering if I could add a few things in our own repository to your plugin.

**Comment by Xericore** [comment]
I do, same as my username at gmail.com. However, I am not planning on adding any larger features to EasyCarts. Mostly because I don't have the time for it. Also, adding more features makes it more difficult to maintain the plugin and keep up with Minecraft changes. Of course if you or anyone else would like to do so I'm fine with it. That's one of the reasons I made this open source :)

**Comment by crazygmr101** [comment]
@Xericore  i emailed you :)

**Pull request merged**
